# Generated by Django 3.0.7 on 2020-06-23 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menus', '0003_auto_20200623_1701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='post_id',
        ),
        migrations.AddField(
            model_name='event',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
