# Generated by Django 3.0.7 on 2020-06-23 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menus', '0005_auto_20200623_1826'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slideshow',
            old_name='Headings',
            new_name='Heading',
        ),
        migrations.RemoveField(
            model_name='event',
            name='image',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='image',
        ),
        migrations.RemoveField(
            model_name='slideshow',
            name='images',
        ),
        migrations.AddField(
            model_name='event',
            name='Image',
            field=models.ImageField(blank=True, upload_to='Menus/Images'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='Image',
            field=models.ImageField(blank=True, upload_to='Menus/Images'),
        ),
        migrations.AddField(
            model_name='slideshow',
            name='Image',
            field=models.ImageField(blank=True, upload_to='Menus/Images'),
        ),
        migrations.AlterField(
            model_name='team',
            name='Image',
            field=models.ImageField(blank=True, upload_to='Menus/Images'),
        ),
    ]
